name: sonic-nova-iac
description: A minimal AWS TypeScript Pulumi program
runtime:
  name: nodejs
  options:
    packagemanager: npm
config:
  pulumi:tags:
    value:
      pulumi:template: aws-typescript
backend:
  url: s3://strata-connectlab-pulumi-backend/teco-bot-poc 